import { Schema } from 'effect'

const Credentials = Schema.Struct({ api_key: Schema.String })
const UpdateEndpoint = Schema.Struct({
  url: Schema.String,
  index: Schema.Number,
  proxies: Schema.Array(Schema.Struct({ url: Schema.String, fingerprint: Schema.String })),
})
const Providers = Schema.Struct({
  movie: Schema.Struct({
    order: Schema.Number,
    name: Schema.String,
    uri: Schema.Array(Schema.String),
  }),
  tvshow: Schema.Struct({
    order: Schema.Number,
    name: Schema.String,
    uri: Schema.Array(Schema.String),
  }),
  anime: Schema.Struct({
    order: Schema.Number,
    name: Schema.String,
    uri: Schema.Array(Schema.String),
  }),
  subtitle: Schema.String,
  metadata: Schema.String,
  torrentCache: Schema.String,
})

/** Every key the legacy `settings.js` defines, with the legacy value types. */
export const SettingsSchema = Schema.Struct({
  projectName: Schema.String,
  projectUrl: Schema.String,
  projectBlog: Schema.String,
  projectForum: Schema.String,
  statusUrl: Schema.String,
  changelogUrl: Schema.String,
  issuesUrl: Schema.String,
  sourceUrl: Schema.String,
  commitUrl: Schema.String,
  dht: Schema.String,
  dhtInfo: Schema.String,
  updateKey: Schema.String,
  opensubtitles: Schema.Struct({ useragent: Schema.String }),
  trakttv: Schema.Struct({ client_id: Schema.String, client_secret: Schema.String }),
  fanart: Credentials,
  tvdb: Credentials,
  tmdb: Credentials,
  providers: Providers,
  trackers: Schema.Struct({
    blacklisted: Schema.Array(Schema.String),
    forced: Schema.Array(Schema.String),
  }),
  theme: Schema.String,
  startScreen: Schema.String,
  lastTab: Schema.String,
  moviesTabEnable: Schema.Boolean,
  seriesTabEnable: Schema.Boolean,
  animeTabEnable: Schema.Boolean,
  favoritesTabEnable: Schema.Boolean,
  watchedTabEnable: Schema.Boolean,
  coversShowRating: Schema.Boolean,
  alwaysShowBookmarks: Schema.Boolean,
  showSeedboxOnDlInit: Schema.Boolean,
  expandedSearch: Schema.Boolean,
  defaultFilters: Schema.String,
  watchedCovers: Schema.String,
  tv_detail_jump_to: Schema.String,
  postersMinWidth: Schema.Number,
  postersMaxWidth: Schema.Number,
  postersMinFontSize: Schema.Number,
  postersMaxFontSize: Schema.Number,
  postersSizeRatio: Schema.Number,
  postersWidth: Schema.Number,
  postersJump: Schema.Array(Schema.Number),
  bigPicture: Schema.Number,
  moviesUITransparency: Schema.String,
  seriesUITransparency: Schema.String,
  nativeWindowFrame: Schema.Boolean,
  alwaysOnTop: Schema.Boolean,
  minimizeToTray: Schema.Boolean,
  events: Schema.Boolean,
  ratingStars: Schema.Boolean,
  showAdvancedSettings: Schema.Boolean,
  language: Schema.String,
  contentLanguage: Schema.String,
  contentLangOnly: Schema.Boolean,
  translateTitle: Schema.String,
  translateEpisodes: Schema.Boolean,
  translateSynopsis: Schema.Boolean,
  translatePosters: Schema.Boolean,
  subtitle_language: Schema.String,
  subtitle_font: Schema.String,
  subtitle_decoration: Schema.String,
  subtitle_size: Schema.String,
  subtitle_color: Schema.String,
  subtitles_bold: Schema.Boolean,
  multipleExtSubtitles: Schema.Boolean,
  opensubtitlesAuthenticated: Schema.Boolean,
  opensubtitlesUsername: Schema.String,
  opensubtitlesPassword: Schema.String,
  playerSubPosition: Schema.String,
  lastWatchedTitle: Schema.String,
  lastWatchedTime: Schema.Union(Schema.Number, Schema.Literal(false)),
  alwaysFullscreen: Schema.Boolean,
  playNextEpisodeAuto: Schema.Boolean,
  preloadNextEpisodeTime: Schema.Number,
  activateLoCtrl: Schema.Boolean,
  chosenPlayer: Schema.String,
  shows_default_quality: Schema.String,
  movies_default_quality: Schema.String,
  playerVolume: Schema.String,
  audioPassthrough: Schema.Boolean,
  activateWatchlist: Schema.Boolean,
  traktStatus: Schema.Boolean,
  traktLastSync: Schema.Union(Schema.Boolean, Schema.String),
  traktLastActivities: Schema.Union(Schema.Boolean, Schema.String),
  traktSyncOnStart: Schema.Boolean,
  traktPlayback: Schema.Boolean,
  activateTorrentCollection: Schema.Boolean,
  toggleSengines: Schema.Boolean,
  enableThepiratebaySearch: Schema.Boolean,
  enable1337xSearch: Schema.Boolean,
  enableSolidTorrentsSearch: Schema.Boolean,
  enableTgxtorrentSearch: Schema.Boolean,
  enableNyaaSearch: Schema.Boolean,
  activateSeedbox: Schema.Boolean,
  activateTempf: Schema.Boolean,
  httpApiEnabled: Schema.Boolean,
  httpApiPort: Schema.Number,
  httpApiUsername: Schema.String,
  httpApiPassword: Schema.String,
  customMoviesServer: Schema.String,
  customSeriesServer: Schema.String,
  customAnimeServer: Schema.String,
  dhtEnable: Schema.String,
  maxActiveTorrents: Schema.Number,
  connectionLimit: Schema.Number,
  maxUdpReqLimit: Schema.Number,
  downloadLimit: Schema.String,
  uploadLimit: Schema.String,
  maxLimitMult: Schema.Number,
  totalDownloaded: Schema.Number,
  totalUploaded: Schema.Number,
  streamPort: Schema.Number,
  continueSeedingOnStart: Schema.Boolean,
  protocolEncryption: Schema.Boolean,
  proxyServer: Schema.String,
  tmpLocation: Schema.String,
  deleteTmpOnClose: Schema.Boolean,
  delSeedboxCache: Schema.String,
  separateDownloadsDir: Schema.Boolean,
  downloadsLocation: Schema.String,
  databaseLocation: Schema.String,
  updateNotification: Schema.String,
  version: Schema.Union(Schema.Boolean, Schema.String),
  dbversion: Schema.String,
  font: Schema.String,
  defaultWidth: Schema.Number,
  defaultHeight: Schema.Number,
  updateEndpoint: UpdateEndpoint,
  arch: Schema.String,
  os: Schema.String,
  releaseName: Schema.String,
})

export type Settings = Schema.Schema.Type<typeof SettingsSchema>
export type SettingsKey = keyof Settings

export const SettingsFields = SettingsSchema.fields
