import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import stylus from 'stylus'

// pnpm scripts run from the repo root, and so does Vitest.
const root = process.cwd()
const stylDir = join(root, 'src/app/styl')
const outDir = join(root, 'resources/themes')
const settingsFile = join(root, 'src/app/settings.js')

const TOKEN_DECLARATION = /^\s*\$([\w-]+)\s*=\s*(.+?)\s*$/gm
const TOKEN_PROPERTY = /--([\w-]+):\s*([^;]+);/g
const COLOUR_VALUE = /^(#[0-9a-f]{3,8}|rgba?\(|hsla?\()/i
const HEX_LITERAL = /^#[0-9a-f]{3,8}$/i

/** Token name from a theme file name, e.g. Official_-_Dark_theme.styl -> Official_-_Dark_theme. */
export function themeNameFromFile(fileName: string): string {
  return fileName.replace(/\.styl$/, '')
}

/** Source with @import lines removed: partials drag in view selectors we don't want. */
export function declarationsOnly(source: string): string {
  return source
    .split('\n')
    .filter((line) => !line.trim().startsWith('@import'))
    .join('\n')
}

function declarationNames(source: string): string[] {
  return [...source.matchAll(TOKEN_DECLARATION)].map((match) => match[1] as string)
}

/** Raw literal hex values, keyed by token: Stylus rewrites #cccccc to #ccc, we keep the source byte. */
function literalHexValues(source: string): Map<string, string> {
  const literals = new Map<string, string>()
  for (const match of source.matchAll(TOKEN_DECLARATION)) {
    const name = match[1] as string
    const raw = (match[2] as string).replace(/\s*\/\/.*$/, '').trim()
    if (HEX_LITERAL.test(raw)) {
      literals.set(name, raw)
    }
  }
  return literals
}

function renderStylus(source: string): Promise<string> {
  return new Promise((resolve, reject) => {
    stylus.render(source, (error, css) => {
      if (error) reject(error)
      else resolve(css)
    })
  })
}

/**
 * Resolves every `$token` in a theme file to its computed CSS value by letting
 * Stylus evaluate the declarations — lighten()/darken()/variable references
 * included. Returns tokens in first-declaration order.
 */
export async function compileTheme(source: string): Promise<Map<string, string>> {
  const declarations = declarationsOnly(source)
  const names = declarationNames(source)
  if (names.length === 0) {
    throw new Error('no token declarations found')
  }

  const properties = names.map((name) => `  --${name}: $${name}`).join('\n')
  const css = await renderStylus(`${declarations}\n:root\n${properties}\n`)

  const values = new Map(
    [...css.matchAll(TOKEN_PROPERTY)].map((m) => [m[1] as string, (m[2] as string).trim()]),
  )
  const literals = literalHexValues(source)
  for (const name of names) {
    if (!values.has(name)) {
      throw new Error(`token --${name} missing from compiled output`)
    }
  }
  return new Map(names.map((name) => [name, literals.get(name) ?? (values.get(name) as string)]))
}

function themeCss(name: string, tokens: Map<string, string>): string {
  const properties = [...tokens.entries()].map(([token, value]) => `  --${token}: ${value};`)
  return [
    '/* Generated by scripts/generate-themes.mts - do not edit. */',
    `:root[data-theme="${name}"] {`,
    ...properties,
    '}',
    '',
  ].join('\n')
}

function tailwindCss(themeTokens: Map<string, Map<string, string>>): string {
  const allThemes = [...themeTokens.values()]
  const colourTokens = [...(allThemes[0]?.keys() ?? [])].filter((token) =>
    allThemes.every((tokens) => COLOUR_VALUE.test(tokens.get(token) ?? '')),
  )
  const imports = [...themeTokens.keys()].map((name) => `@import "./${name}.css";`)
  const scale = colourTokens.map((token) => `  --color-${token}: var(--${token});`)
  return [
    '/* Generated by scripts/generate-themes.mts - do not edit. */',
    ...imports,
    '',
    '@theme inline {',
    ...scale,
    '}',
    '',
  ].join('\n')
}

async function legacyDefaultTheme(): Promise<string> {
  const settings = await readFile(settingsFile, 'utf8')
  const match = /Settings\.theme\s*=\s*'([^']+)'/.exec(settings)
  if (!match) {
    throw new Error(`could not find "Settings.theme = '...'" in ${settingsFile}`)
  }
  return match[1] as string
}

export interface GeneratedTheme {
  name: string
  tokens: Map<string, string>
}

/** Reads the Stylus themes, writes resources/themes/*.css + themes.json, returns what it wrote. */
export async function generateAll(): Promise<GeneratedTheme[]> {
  const files = (await readdir(stylDir)).filter((file) => file.endsWith('_theme.styl')).sort()
  if (files.length === 0) {
    throw new Error(`no *_theme.styl files in ${stylDir}`)
  }

  const themes: GeneratedTheme[] = []
  for (const file of files) {
    const source = await readFile(join(stylDir, file), 'utf8')
    themes.push({ name: themeNameFromFile(file), tokens: await compileTheme(source) })
  }

  await mkdir(outDir, { recursive: true })
  for (const theme of themes) {
    await writeFile(join(outDir, `${theme.name}.css`), themeCss(theme.name, theme.tokens), 'utf8')
  }

  const themeMap = new Map(themes.map((theme) => [theme.name, theme.tokens]))
  await writeFile(join(outDir, 'index.css'), tailwindCss(themeMap), 'utf8')

  const defaultTheme = await legacyDefaultTheme()
  if (!themeMap.has(defaultTheme)) {
    throw new Error(`default theme "${defaultTheme}" has no theme file`)
  }
  const manifest = JSON.stringify(
    { default: defaultTheme, themes: themes.map((t) => t.name) },
    null,
    2,
  )
  await writeFile(join(outDir, 'themes.json'), `${manifest}\n`, 'utf8')

  return themes
}

if ((process.argv[1] ?? '').endsWith('generate-themes.mts')) {
  const themes = await generateAll()
  const counts = themes.map((theme) => `${theme.name} (${theme.tokens.size} tokens)`).join(', ')
  console.log(`Generated ${themes.length} themes: ${counts}`)
}
